apiVersion: v1
kind: ConfigMap
metadata:
  name: lastmile-config
  namespace: lastmile
data:
  AUTH_PORT: "4000"
  AUTH_GRPC_PORT: "50051"

  DRIVER_PORT: "3002"
  DRIVER_GRPC_PORT: "50052"

  RIDER_PORT: "4003"
  RIDER_GRPC_PORT: "50054"

  LOCATION_PORT: "4004"
  LOCATION_GRPC_PORT: "50055"

  MATCHING_PORT: "3005"
  STATION_PORT: "5002"
