---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: driver-service-hpa
  namespace: lastmile
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: driver-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rider-service-hpa
  namespace: lastmile
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rider-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: matching-service-hpa
  namespace: lastmile
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: matching-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: location-service-hpa
  namespace: lastmile
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: location-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
