apiVersion: apps/v1
kind: Deployment
metadata:
  name: rider-service
  namespace: lastmile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rider-service
  template:
    metadata:
      labels:
        app: rider-service
    spec:
      containers:
        - name: rider-service
          image: sathwik049/lastmile-rider_service:latest
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: lastmile-config
                  key: RIDER_PORT
            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: lastmile-config
                  key: RIDER_GRPC_PORT
            - name: MONGO_URI
              value: "mongodb://mongodb.lastmile.svc.cluster.local:27017/lastmile_db"
          ports:
            - containerPort: 4003
            - containerPort: 50054
---
apiVersion: v1
kind: Service
metadata:
  name: rider-service
  namespace: lastmile
spec:
  selector:
    app: rider-service
  ports:
    - name: http
      port: 4003
      targetPort: 4003
    - name: grpc
      port: 50054
      targetPort: 50054

